Add UniqueFactory for creating random string or int from given range
flow-php/flow pull request #1128
Opened 2024-07-20 21:48 UTC by mleczakm

<h2>Change Log</h2>
<div id="change-log">
  <h4>Added</h4>
  <ul id="added">
     <li>UniqueFactory as source of random ints/strings with given length</li> 
  </ul> 
  <h4>Fixed</h4>  
  <ul id="fixed">
    
  </ul>
  <h4>Changed</h4>
  <ul id="changed">
    
  </ul>  
  <h4>Removed</h4>
  <ul id="removed">
    
  </ul>
  <h4>Deprecated</h4>
  <ul id="deprecated">
    
  </ul>  
  <h4>Security</h4> 
  <ul id="security">
    
  </ul>     
</div>
<hr/>

<h2>Description</h2>

Solves https://github.com/flow-php/flow/issues/1124

2024-07-21 07:01 UTC, stloyd commented on src/core/etl/src/Flow/ETL/UniqueFactory.php
> +class UniqueFactory
```suggestion
final class UniqueFactory
```

2024-07-21 07:01 UTC, stloyd commented on src/core/etl/src/Flow/ETL/UniqueFactory.php
> +    public static function int(int $min, int $max) : int
Maybe also:
```suggestion
    private function __construct()
    {}

    public static function int(int $min, int $max) : int
```
Cause this class has only static methods.

2024-07-21 07:01 UTC, stloyd commented on src/core/etl/src/Flow/ETL/UniqueFactory.php
> +        return \mb_substr(\bin2hex(\random_bytes($bytes)), 0, \max(0, $int));
I think we don't need multibyte here, do we?

2024-07-21 07:01 UTC, stloyd commented on src/core/etl/tests/Flow/ETL/Tests/Integration/DataFrame/PartitioningTest.php
> -                        $maxItems = \random_int(2, 10);
More I look at this, more I think I would add new function for unique int/string to "hide" object call & improve DX perspective, WDYT?

2024-07-21 08:45 UTC, norberttech commented
The PR look good and we could merge it like that (beside few small things @stloyd pointed out) but I think we might be able to still improve even more. Here are my thoughts. 

**Naming** - now when I look at it something is missing in the name, like `RandomValueGenerator` would be more descriptive. 

**Dependency Injection** - I think I would turn `RandomValueGenerator` into an interface with `NativePHPRandomValueGenerator` that we can simply inject into objects that would need a unique values (I'm thinking about caching strategies here and more advanced data processing algorithms). Additionally (but maybe in another PR) we could also create Flow scalar functions that could be used during data processing. 

**DSL Functions** - as pointed by @stloyd we probably should also add `generate_random_string(int $length = 16)` and `generate_random_int(int $start = PHP_INT_MIN, int $end = PHP_INT_MAX, RandomValueGenerator $generator = new NatievPHPRandomValueGenerator())` functions so we can use them in tests instead of static factories.

2024-07-22 20:01 UTC, mleczakm commented on src/core/etl/src/Flow/ETL/UniqueFactory.php
> +        return \mb_substr(\bin2hex(\random_bytes($bytes)), 0, \max(0, $int));
```suggestion
        return \substr(\bin2hex(\random_bytes($bytes)), 0, \max(0, $int));
```

2024-07-24 11:18 UTC, norberttech requested changes
Some changes described above are required to merge this PR :)

2024-07-31 06:08 UTC, norberttech approved these changes

2024-07-31 06:08 UTC, merged